import { Injectable, Logger, OnModuleInit, OnModuleDestroy } from '@nestjs/common';
import { WebSocketServer, WebSocket } from 'ws';
import { TradingEngine, HftSignal } from '../engine/trading.engine';
import { MarketTick } from '@wertbot/shared-types';

@Injectable()
export class TradingGateway implements OnModuleInit, OnModuleDestroy {
  private readonly logger = new Logger(TradingGateway.name);
  private wss: WebSocketServer | null = null;
  private readonly clients = new Set<WebSocket>();

  constructor(private readonly tradingEngine: TradingEngine) {}

  onModuleInit() {
    this.initWebSocketServer();
    this.listenToEngineSignals();
  }

  onModuleDestroy() {
    if (this.wss) {
      this.wss.close();
      this.wss = null;
    }
  }

  private initWebSocketServer() {
    try {
      const port = Number(process.env.WS_PORT || 3004);
      this.wss = new WebSocketServer({ port });
      this.logger.log(`✅ Trading WebSocket Gateway listening on ws://localhost:${port}`);

      this.wss.on('connection', (ws: WebSocket) => {
        this.clients.add(ws);
        this.logger.log(`Client connected to Trading WS feed (Total: ${this.clients.size})`);

        ws.send(
          JSON.stringify({
            event: 'connected',
            message: 'Connected to WertBot HFT Market Stream',
            timestamp: Date.now(),
          }),
        );

        ws.on('message', (message: string) => {
          try {
            const data = JSON.parse(message);
            if (data.event === 'ping') {
              ws.send(JSON.stringify({ event: 'pong', timestamp: Date.now() }));
            }
          } catch {
            /* ignore invalid json */
          }
        });

        ws.on('close', () => {
          this.clients.delete(ws);
          this.logger.log(`Client disconnected from Trading WS feed`);
        });

        ws.on('error', (err) => {
          this.logger.warn(`WS client error: ${err.message}`);
          this.clients.delete(ws);
        });
      });
    } catch (err) {
      this.logger.warn(`WebSocket Gateway initialization deferred: ${(err as Error).message}`);
    }
  }

  /**
   * Broadcasts market tick data to all connected WebSockets.
   */
  broadcastTick(tick: MarketTick): void {
    const payload = JSON.stringify({ event: 'tick', data: tick });
    for (const client of this.clients) {
      if (client.readyState === WebSocket.OPEN) {
        client.send(payload);
      }
    }
  }

  /**
   * Broadcasts HFT AI signals generated by analysis workers.
   */
  broadcastSignal(signal: HftSignal): void {
    const payload = JSON.stringify({ event: 'ai_signal', data: signal });
    for (const client of this.clients) {
      if (client.readyState === WebSocket.OPEN) {
        client.send(payload);
      }
    }
  }

  private listenToEngineSignals(): void {
    this.tradingEngine.on('signal', (signal: HftSignal) => {
      this.broadcastSignal(signal);
    });
  }
}
